language: ruby
dist: xenial
cache: bundler

script: bundle exec rspec

matrix:
  include:
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 2.7
    - rvm: 2.6
      env: COVERAGE=PartialSummary,Coveralls
    - rvm: truffleruby
    - rvm: jruby-head
      env: JRUBY_OPTS="--debug -X+O"
    - rvm: ruby-head
    - rvm: 2.6
      os: osx
    - rvm: 2.6
      os: osx
      gemfile: gems/nio4r-2.3.gemfile
    - rvm: 2.7
  allow_failures:
    - rvm: ruby-head
    - rvm: truffleruby
    - rvm: jruby-head
