name: Development

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{matrix.os}}-latest
    continue-on-error: ${{matrix.experimental}}
    
    strategy:
      matrix:
        os:
          - ubuntu
          - macos
        
        ruby:
          - 2.5
          - 2.6
          - 2.7
        
        experimental: [false]
        env: [""]
        
        include:
          - experimental: true
            os: ubuntu
            ruby: truffleruby
            env: JRUBY_OPTS="--debug -X+O"
          - experimental: true
            os: ubuntu
            ruby: jruby
          - experimental: true
            os: ubuntu
            ruby: head
          - experimental: false
            os: ubuntu
            ruby: 2.6
            env: COVERAGE=PartialSummary,Coveralls
          - experimental: false
            os: macos
            ruby: 2.7
            env: BUNDLE_GEMFILE=gems/nio4r-2.3.gemfile
    
    steps:
    - uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
    
    - name: Install dependencies
      run: ${{matrix.env}} bundle install
    
    - name: Run tests
      run: ${{matrix.env}} bundle exec rspec
